site_name: Dragon Customer Support
site_description: Dragon Customer Support Center

theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    scheme: default
    primary: blue
    accent: blue

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
